# Generated by Django 5.1.1 on 2024-10-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=30)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.room')),
                ('uploaded_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherprofile')),
            ],
        ),
    ]
