# Generated by Django 5.1.1 on 2024-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(null=True, upload_to='assignments'),
        ),
    ]
