# Generated by Django 5.1.1 on 2024-10-11 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_assignment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherprofile'),
        ),
    ]
